Window.SetBackgroundTopColor(0.035, 0.038, 0.043);
Window.SetBackgroundBottomColor(0.035, 0.038, 0.043);

logo = Image.Text("FlexOS", 0.82, 0.83, 0.86);
logo_sprite = Sprite(logo);
logo_sprite.SetX(Window.GetWidth()/2 - logo.GetWidth()/2);
logo_sprite.SetY(Window.GetHeight()/2 - logo.GetHeight()/2);

status = Image.Text("Starting", 0.43, 0.45, 0.48);
status_sprite = Sprite(status);
status_sprite.SetX(Window.GetWidth()/2 - status.GetWidth()/2);
status_sprite.SetY(Window.GetHeight()/2 + logo.GetHeight());

fun message_callback(text) {
    status = Image.Text(text, 0.43, 0.45, 0.48);
    status_sprite.SetImage(status);
    status_sprite.SetX(Window.GetWidth()/2 - status.GetWidth()/2);
}
Plymouth.SetMessageFunction(message_callback);
