---
dontChroot: false
timeout: 14400
packagechooser_desktop:
    kde: "/usr/lib/flexos/flex-desktop-install kde ${gs[username]}"
    gnome: "/usr/lib/flexos/flex-desktop-install gnome ${gs[username]}"
    hyprland: "/usr/lib/flexos/flex-desktop-install hyprland ${gs[username]}"
