---
dontChroot: false
timeout: 7200
packagechooser_desktop:
    kde: "/usr/lib/flexos/flex-desktop-install kde ${USER}"
    gnome: "/usr/lib/flexos/flex-desktop-install gnome ${USER}"
    hyprland: "/usr/lib/flexos/flex-desktop-install hyprland ${USER}"
