---
dontChroot: false
timeout: 7200
packagechooser_desktop:
    kde: "/usr/lib/flexos/flex-desktop-install kde"
    gnome: "/usr/lib/flexos/flex-desktop-install gnome"
    cinnamon: "/usr/lib/flexos/flex-desktop-install cinnamon"
    deepin: "/usr/lib/flexos/flex-desktop-install deepin"
    xfce: "/usr/lib/flexos/flex-desktop-install xfce"
    mate: "/usr/lib/flexos/flex-desktop-install mate"
    lxqt: "/usr/lib/flexos/flex-desktop-install lxqt"
    i3: "/usr/lib/flexos/flex-desktop-install i3"
    sway: "/usr/lib/flexos/flex-desktop-install sway"
    hyprland: "/usr/lib/flexos/flex-desktop-install hyprland"
    budgie: "/usr/lib/flexos/flex-desktop-install budgie"
    cosmic: "/usr/lib/flexos/flex-desktop-install cosmic"
    pantheon: "/usr/lib/flexos/flex-desktop-install pantheon"
    ukui: "/usr/lib/flexos/flex-desktop-install ukui"
    regolith: "/usr/lib/flexos/flex-desktop-install regolith"
    enlightenment: "/usr/lib/flexos/flex-desktop-install enlightenment"
    trinity: "/usr/lib/flexos/flex-desktop-install trinity"
