---
dontChroot: false
timeout: 7200
packagechooser_packageprofile:
    minimal: "/usr/lib/flexos/flex-package-profile-install minimal"
    standard: "/usr/lib/flexos/flex-package-profile-install standard"
    gaming: "/usr/lib/flexos/flex-package-profile-install gaming"
    developer: "/usr/lib/flexos/flex-package-profile-install developer"
    creator: "/usr/lib/flexos/flex-package-profile-install creator"
