---
dontChroot: false
timeout: 900
verbose: true

script:
  - command: "/usr/bin/python3 /usr/lib/flexos/flex-postinstall"
    timeout: 900
    verbose: true

i18n:
  name: "Finalizing FlexOS"
  name[tr]: "FlexOS son ayarları uygulanıyor"
